import { Product } from '@prisma/client';
import { Decimal } from '@prisma/client/runtime/library';

export const mockProducts: Product[] = [
  {
    id: 'prod_1',
    name: 'Paris at Sunset',
    description: 'Golden hour over the Seine — a timeless classic.',
    price: new Decimal(49.99),
    imageUrl: 'https://d1r1t0ctsj0cph.cloudfront.net/test.jpg',
    stock: 50,
    category: 'travel',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'prod_2',
    name: 'Tokyo Neon Nights',
    description: 'Shibuya crossing alive with light and energy.',
    price: new Decimal(49.99),
    imageUrl: 'https://d1r1t0ctsj0cph.cloudfront.net/test.jpg',
    stock: 35,
    category: 'travel',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'prod_3',
    name: 'Happy Birthday Balloons',
    description: 'Bright and cheerful — perfect for any birthday.',
    price: new Decimal(34.99),
    imageUrl: 'https://d1r1t0ctsj0cph.cloudfront.net/test.jpg',
    stock: 80,
    category: 'birthday',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'prod_4',
    name: 'New York Skyline',
    description: 'Manhattan at midnight — the city that never sleeps.',
    price: new Decimal(49.99),
    imageUrl: 'https://d1r1t0ctsj0cph.cloudfront.net/test.jpg',
    stock: 60,
    category: 'travel',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'prod_5',
    name: 'Thank You Florals',
    description: 'Delicate watercolour flowers for a heartfelt thank you.',
    price: new Decimal(34.99),
    imageUrl: 'https://d1r1t0ctsj0cph.cloudfront.net/test.jpg',
    stock: 90,
    category: 'thank-you',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'prod_6',
    name: 'Vintage London',
    description: 'Red telephone boxes and black cabs — classic London.',
    price: new Decimal(49.99),
    imageUrl: 'https://d1r1t0ctsj0cph.cloudfront.net/test.jpg',
    stock: 45,
    category: 'travel',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];
